#!/bin/bash

##01##

## IDENTIFY SDA

# root
RootN=3

# swap
SwapN=2

#UEFI
UEFIN=1

## FORMAT PARTITIONS

# Root
mkfs.ext4 /dev/sda$RootN

# Swap
mkswap /dev/sda$SwapN

#UEFI
mkfs.fat -F32 /dev/sda$UEFIN

## Mount partitions

# Root
mount /dev/sda$RootN /mnt

# Swap
swapon /dev/sda$SwapN

#UEFI
mkdir /mnt/efi
mount /dev/sda$UEFIN /mnt/efi

