#!/bin/bash

##01##

# Partition the disks
#UEFI
UEFIN=1
# swap
SwapN=2
# root
RootN=3


# Format the partitions
#UEFI
mkfs.fat -F32 /dev/sda$UEFIN
# Swap
mkswap /dev/sda$SwapN
# Root
mkfs.ext4 /dev/sda$RootN



# Mount the file systems
#UEFI
mkdir /mnt/efi
mount /dev/sda$UEFIN /mnt/efi
# Swap
swapon /dev/sda$SwapN
# Root
mount /dev/sda$RootN /mnt
