#!/bin/bash

##04##

## Generating system locale
nano /etc/locale.gen

# Uncomment
# en_US.UTF-8:

# Generate the locale
locale-gen

echo "LANG=en_US.UTF-8" >> /etc/locale.conf

# Select the system language
localectl set-locale LANG=en_US.UTF-8

# Time zone
tzselect

# choosing your area
ln -sf /usr/share/zoneinfo/America/La_Paz /etc/localtime
hwclock --systohc
