#!/bin/bash

##06##

## INSTALL & CONFIGURE BOOTLOADER

#UEFI
UN=1

# root
RN=3

pacman -S refind

# refind-install --usedefault /dev/sda$UN --alldrivers
# mkrlconf

refind-install 

echo ""Boot using default options"" >> /boot/refind_linux.conf

blkid /dev/sda$RN >> /boot/refind_linux.conf

echo "rw add_efi_memmap initrd=boot\intel-ucode.img initrd=boot\initramfs-linux.img" >> /boot/refind_linux.conf

nano /boot/refind_linux.conf

# "Boot using default options" "root=PARTUUID=xxx rw add_efi_memmap initrd=boot\intel-ucode.img initrd=boot\initramfs-linux.img"

