#!/bin/bash

##07##

## COMPUTER NAME & HOST

echo root:password | chpasswd

echo Arco > /etc/hostname

echo "127.0.0.1 localhost" >> /etc/hosts

echo "::1       localhost" >> /etc/hosts

echo "127.0.0.1 Arco" >> /etc/hosts

nano /etc/hosts

