#!/bin/bash

##08##

# Post-installation
pacman -S wpa_supplicant wireless_tools networkmanager nm-connection-editor network-manager-applet  pavucontrol pulseaudio alsa-utils sof-firmware alsa-ucm-conf tlp ntfs-3g dialog base-devel rsync reflector xdg-user-dirs xdg-utils
systemctl enable NetworkManager.service
systemctl enable tlp

