#!/bin/bash

##08##

## REGULAR USER

pacman -S sudo

useradd -m -G wheel,storage,power mechalar

#echo ermanno:password | chpasswd
password mechalar

EDITOR=nano visudo

# Uncomment
# %wheel ALL=(ALL) ALL

