#!/bin/bash

##13##

## INSTALL & ENABLE NETWORK -AUDIO

pacman -S wpa_supplicant wireless_tools networkmanager  network-manager-applet dialog pavucontrol  alsa-utils sof-firmware tlp firefox gnome-tweaks

systemctl enable NetworkManager.service
systemctl enable tlp
sudo systemctl enable gdm
# systemctl enable lightdm.service

